name: Housekeeping - Issues management
description: Automated issue management policy for Arc Jumpstart repository
owner: azure-arc-admin
resource: repository
disabled: false
where: 
configuration:
  resourceManagementConfiguration:
    scheduledSearches:
    - description: Mark issues as stale when needing author feedback
      frequencies:
      - hourly:
          hour: 3
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: needs author feedback
      - noActivitySince:
          days: 10
      - isNotLabeledWith:
          label: no recent activity
      actions:
      - addLabel:
          label: no recent activity
      - addReply:
          reply: This issue has been automatically marked as stale because it has been marked as requiring author feedback but has not had any activity for **10 days**. It will be closed if no further activity occurs **within 7 days of this comment**. Thank you ${issueAuthor} for your contributions!
    - description: Close stale issues after warning period
      frequencies:
      - hourly:
          hour: 3
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: no recent activity
      - noActivitySince:
          days: 14
      actions:
      - addReply:
          reply: Because of no activity for over **14 days**, we're closing this issue. Please open a new issue report if more support is required. Thank you for your support ${issueAuthor}!
      - closeIssue
    - description: Notify assignees of issues needing investigation
      frequencies:
      - hourly:
          hour: 12
      filters:
      - isOpen
      - isIssue
      - hasLabel:
          label: investigate
      - noActivitySince:
          days: 3
      actions:
      - addReply:
          reply: "${assignees}\nGentle ping that this issue needs attention. "
    eventResponderTasks:
    - if:
      - payloadType: Issues
      - isAction:
          action: Opened
      then:
      - addReply:
          reply: 'Hi ${issueAuthor}! Thank you for opening this issue in the Arc Jumpstart repository. Our team actively monitors these issues and we will review it soon. Please make sure to:

          1. Check our documentation and existing issues first
          2. Provide as much detail as possible
          3. Include any relevant logs or error messages
          
          We appreciate your contribution to making Arc Jumpstart better!'
      description: Send welcome message to new issue authors
    - if:
      - payloadType: Issue_Comment
      - hasLabel:
          label: no recent activity
      - isAction:
          action: Created
      - isOpen
      then:
      - removeLabel:
          label: no recent activity
      - addLabel:
          label: investigate
      description: 
    - if:
      - payloadType: Issues
      - not:
          isAction:
            action: Closed
      - hasLabel:
          label: no recent activity
      - not:
          labelAdded:
            label: no recent activity
      then:
      - removeLabel:
          label: no recent activity
      description: 
    - if:
      - payloadType: Issue_Comment
      then:
      - cleanEmailReply
      description: 
    - if:
      - payloadType: Issue_Comment
      - isActivitySender:
          issueAuthor: True
      - or:
        - hasLabel:
            label: needs author feedback
        - hasLabel:
            label: no recent activity
      then:
      - removeLabel:
          label: needs author feedback
      - removeLabel:
          label: no recent activity
      - addLabel:
          label: review
      description: 
onFailure: 
onSuccess:
