apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  - host: {JS_HOST}
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: bookstore
            port:
              number: 14001
        path: /bookstore
      - pathType: ImplementationSpecific
        backend:
          service:
            name: bookstore-v2
            port:
              number: 14001
        path: /bookstore-v2
---
kind: IngressBackend            # Ingress Backend for Bookstore App
apiVersion: policy.openservicemesh.io/v1alpha1
metadata:
  name: backend
spec:
  backends:
  - name: bookstore
    port:
      number: 14001
      protocol: http
  - name: bookstore-v2
    port:
      number: 14001
      protocol: http
  sources:
  - kind: Service
    namespace: ingress-nginx
    name: ingress-nginx-controller
