name: Issue or Bug Report
description: File an issue or bug report.
title: "[Issue/Bug]: "
labels: ['bug', 'triage needed']
projects: ["microsoft/162"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this issue or bug report!
  - type: dropdown
    id: jumpstart-solution
    attributes:
      label: Jumpstart Solution
      multiple: true
      description: What Jumpstart solution you are running?
      options:
        - Jumpstart ArcBox
        - Jumpstart HCIBox
        - Jumpstart Agora
        - A specific Jumpstart scenario
        - Jumpstart Drops
        - Other
    validations:
      required: true