name: Bug Report
description: File an issue or bug report.
title: "[Issue/Bug]: "
labels: ['bug', 'triage needed']
projects: ["microsoft/162"]
body:
  - type: markdown
    attributes:
      value: |
        🙏Thanks for taking the time to fill out this issue or bug report!
        ⚠️ If your bug report is related to documentation, we kindly ask you to open both an issue and a PR in our [documentation repository](https://github.com/Azure/arc_jumpstart_docs).
        🛑 The intent of this "Bug report" template is to address feature requests related to the various Arc Jumpstart solution. The Arc Jumpstart team does not handle and/or support Azure Arc upstream core product related issues, bugs and feature requests and will try to assist on a best effort basis. For a core product issue or feature request/feedback, please create an official [Azure support ticket](https://azure.microsoft.com/support/create-ticket/) or [general feedback request](https://feedback.azure.com). 
  - type: dropdown
    id: jumpstart-solution
    attributes:
      label: Jumpstart Solution
      multiple: true
      description: What Jumpstart solution you are running?
      options:
        - Jumpstart ArcBox
        - Jumpstart HCIBox
        - Jumpstart Agora
        - A specific Jumpstart scenario
        - Jumpstart Drops
        - Other
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen and how to reproduce?
      placeholder: Tell us what you see! If applicable, add screenshots to help explain your problem.
    validations:
      required: true
  - type: input
    id: solution-url
    attributes:
      label: We need a URL
      description: Share with us the URL to the Jumpstart solution you are running
      placeholder: ex. https://jumpstart.azure.com/azure_jumpstart_arcbox/ITPro
    validations:
      required: true
  - type: dropdown
    id: deployment-method
    attributes:
      label: Deployment Method
      multiple: true
      description: What deployment method you are using?
      options:
        - Azure Portal
        - Azure CLI
        - PowerShell
        - Bicep
        - ARM Template
        - Other
    validations:
      required: true      
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output. Make sure to include any sensitive information or passwords.
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
