apiVersion: v1 
kind: PersistentVolumeClaim 
metadata:
    ### CREATE A NAME FOR YOUR PVC ###
    name: esacontainerpvc
    ### USE A NAMESPACE THAT MATCHES YOUR INTENDED CONSUMING POD OR "DEFAULT" ###
    namespace: azure-iot-operations
spec: 
    accessModes: 
        - ReadWriteMany 
    resources: 
        requests: 
            storage: 5Gi 
    storageClassName: esa
    volumeMode: Filesystem
    ### THIS NAME IS FROM YOUR PV CONFIG ###
    volumeName: esacontainerpv
status: 
    accessModes: 
        - ReadWriteMany 
    capacity: 
        storage: 5Gi